### ISSUE TITLE
Detailed processing of JAVA dataset

### ISSUE THREAD

**Issue by PikachuHy** [LiuFang816/xl_mt_code_completion#2]
hi, 
I am very confused about the details of the java dataset.
For example, the 103rd node of the first sample in the train.json.
![image](https://user-images.githubusercontent.com/18223871/112740613-e097e880-8fb0-11eb-82c2-0208e1016c76.png)

The value of this node are 'gitRepositoryMock' and 'getInfo'.
How do we handle this case?
Shall we directly use the first and discard the second?

Can you share the **pickle data** used in your model? Just like the Pointer Mixture Network in your paper.
https://github.com/jack57lee/neuralCodeCompletion
https://drive.google.com/open?id=1EZZuL8Rl3tatvxpIClvO_a8JD_Oid_oY

thanks.

**Comment by zhangyue-se** [comment]
Hi,did this model finally run successfully with your own data set?

**Comment by PikachuHy** [comment]
We just use Python, JavaScript, Java.

**Comment by LiuFang816** [comment]
We use '_' to join the values. I will upload the pickle files to the google drive address. (https://drive.google.com/open?id=1xxnYAu8L5i6TpNpMNDWxSNsOs3XYxS6T)
